export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const INVALID_CREDS = 'INVALID_CREDS';


export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';


export const PATIENT_DETAILS = 'PATIENT_DETAILS';
export const DOCTOR_DETAILS = 'DOCTOR_DETAILS'

//noti
export const FETCH_DETAILS = "FETCH_DETAILS";
export const FILTER_BY_DATE = "FILTER_BY_DATE";
export const FILTER_BY_FUTURE_DATE = "FILTER_BY_FUTURE_DATE";
export const FILTER_BY_MISSED_DATE = "FILTER_BY_MISSED_DATE";
export const FILTER_PENDING_REQUEST = "FILTER_PENDING_REQUEST";
export const LOAD_DATA = "LOAD_DATA";

export const ACTIVE_TAB = "ACTIVE_TAB";

//Consultation Types Start
export const ADD_NEW_PATIENT = "ADD_NEW_PATIENT";
export const WRITE_DOCTOR_NOTE = 'WRITE_DOCTOR_NOTE';
export const WRITE_PSYCHO_NOTE = 'WRITE_PSYCHO_NOTE';
export const GET_DOCTOR_NOTES = 'GET_DOCTOR_NOTE';
export const GET_PSYCHO_NOTES = 'GET_PSYCHO_NOTES';
export const GET_PATIENTS_LIST = 'GET_PATIENTS_LIST';
export const SET_SELECTED_PATIENT = 'SET_SELECTED_PATIENT';
export const SAVE_DOCTOR_NOTE = 'SAVE_DOCTOR_NOTE';
export const PATIENT_CREATED = 'PATIENT_CREATED';
export const NAVIGATE_BACK = 'NAVIGATE_BACK';
export const UPDATE_PATIENT_LIST = 'UPDATE_PATIENT_LIST';
export const RESET_PATIENT_INFO = 'RESET_PATIENT_INFO';
export const EDIT_PSYCHO_NOTES = 'EDIT_PSYCHO_NOTES';
export const RESET_WRITE_DOCTOR_NOTE = 'RESET_WRITE_DOCTOR_NOTE';

//Consultation Types End

//Manage Patients Start
export const GET_MANAGE_PATIENTS = 'GET_MANAGE_PATIENT';
export const GET_PATIENT_HISTORY = 'GET_PATIENT_HISTORY';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
export const SET_SELECTED_NOTE = 'SET_SELECTED_NOTE';
//Manage Patients End

//Add Schedule start 
export const ADD_NEW_SCHEDULE = 'ADD_NEW_SCHEDULE';
export const GET_SCHEDULES = 'GET_SCHEDULES';
export const SAVE_SCHEDULE = 'SAVE_SCHEDULE';
export const MODIFY_SCHEDULE = 'MODIFY_SCHEDULE';
export const GET_SCHEDULES_BY_ID = 'GET_SCHEDULES_BY_ID';
export const SCHEDULE_DATA = 'SCHEDULE_DATA';
//Add Schedule end

//Save Prescription
export const SAVE_PRESCRIPTION = 'SAVE_PRESCRIPTION';
export const GET_PRESCRIPTION = 'GET_PRESCRIPTION';
export const GET_DRUG_DETAILS_LIST = 'GET_DRUG_DETAILS_LIST';
export const GET_DRUG_COMPOUND_LIST = 'GET_DRUG_COMPOUND_LIST';
export const GET_DRUG_SIDE_EFFECTS = 'GET_DRUG_SIDE_EFFECTS';
export const GET_PRESCRIPTION_DRUG_DETAILS_LIST = 'GET_PRESCRIPTION_DRUG_DETAILS_LIST';
export const CST = 'CST'
export const NAVIGATE_BACK_PSYC_NOTE = 'NAVIGATE_BACK_PSYC_NOTE'
export const GET_PRESCRIPTION_BRAND_DETAILS_LIST = 'GET_PRESCRIPTION_BRAND_DETAILS_LIST'

export const CLEAR_BRAND_LIST = 'CLEAR_BRAND_LIST';
export const CLEAR_SIDE_EFEECT_LIST = 'CLEAR_SIDE_EFEECT_LIST';
export const GET_DOCTOR_NOTES_FOR_PRES = 'GET_DOCTOR_NOTES_FOR_PRES';
export const GET_DRUG_COMPOUND_LIST_FOR_PRES = 'GET_DRUG_COMPOUND_LIST_FOR_PRES'
export const EDIT_DOCTOR_NOTES = "EDIT_DOCTOR_NOTES";
export const SEND_PRESCRIPTION_FROM_CST = 'SEND_PRESCRIPTION_FROM_CST';
export const GET_DRUG_SIDE_EFFECTS_FOR_PRES = 'GET_DRUG_SIDE_EFFECTS_FOR_PRES'
export const GET_PROFILE_DETAILS = 'GET_PROFILE_DETAILS';

//noti

// Activity Tracker
export const GET_PATIENT_HABIT_DATA = 'GET_PATIENT_HABIT_DATA';
export const GET_PATIENT_MOOD_DATA = 'GET_PATIENT_MOOD_DATA';
export const GET_PATIENT_TASK_DATA = 'GET_PATIENT_TASK_DATA';
export const GET_PATIENT_PILL_DATA = 'GET_PATIENT_PILL_DATA';
export const GET_PATIENT_PILL_CONFIG_DATA = 'GET_PATIENT_PILL_CONFIG_DATA';
export const GET_PATIENT_HABIT_CONFIG_DATA = 'GET_PATIENT_HABIT_CONFIG_DATA';
export const GET_PATIENT_TASK_CONFIG_DATA = 'GET_PATIENT_TASK_CONFIG_DATA';